services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres-shard-1:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auction_db_1
    ports:
      - "5432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data

  postgres-shard-2:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auction_db_2
    ports:
      - "5433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data

  bidding-service:
    build: .
    command: ["./bidding_svc"]
    ports:
      - "50051:50051"
    environment:
      - REDIS_ADDR=redis:6379
      - KAFKA_ADDR=kafka:29092
      - DB_SHARD_1_DSN=postgres://user:password@postgres-shard-1:5432/auction_db_1
      - DB_SHARD_2_DSN=postgres://user:password@postgres-shard-2:5432/auction_db_2
    depends_on:
      - postgres-shard-1
      - postgres-shard-2
      - redis
      - kafka

  auction-service:
    build: .
    command: ["./auction_svc"]
    ports:
      - "50052:50052"
    environment:
      - DB_SHARD_1_DSN=postgres://user:password@postgres-shard-1:5432/auction_db_1
    depends_on:
      - postgres-shard-1

  notification-service:
    build: .
    command: ["./notification_svc"]
    environment:
      - KAFKA_ADDR=kafka:29092
    depends_on:
      - kafka

  gateway-service:
    build: .
    command: ["./gateway_svc"]
    ports:
      - "8081:8081"
    environment:
      - BIDDING_SVC_ADDR=bidding-service:50051
      - AUCTION_SVC_ADDR=auction-service:50052
    depends_on:
      - bidding-service
      - auction-service

volumes:
  pgdata1:
  pgdata2: